---
service: demo
provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    STAGE: ${self:provider.stage}

package:
  exclude:
    - README.md
    - LICENSE

functions:
  api:
    handler: api.handler
    description: OpenAPI Hello World!
    events:
      - http: ANY /
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    usePipenv: true
